# Generated by Django 2.2 on 2020-10-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_subcription_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='address',
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='address_type',
            field=models.CharField(blank=True, choices=[('B', 'Billing')], max_length=1),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Email Id'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='fname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='lname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='seller_msg',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='tax',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Service Charges'),
        ),
    ]
